apiVersion : apps/v1
kind: Deployment
metadata:
  name: "ctpsserjeaks01-59b2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "ctpsserjeaks01-59b2"
  template:
    metadata:
      labels:
        app: "ctpsserjeaks01-59b2"
    spec:
      containers:
        - name: "ctpsserjeaks01-59b2"
          image: "ctpsserjecr01.azurecr.io/ctpsserjeaks01"
          ports:
          - containerPort: 80