on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: uksqqbe002crc01.azurecr.io
        username: ${{ secrets.acr_uksqqbe002crc01_username }}
        password: ${{ secrets.acr_uksqqbe002crc01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/WebApplication1" -f  "WebApplication1/Dockerfile" -t uksqqbe002crc01.azurecr.io/uksqqbe002aks01:${{ github.sha }}
        docker push uksqqbe002crc01.azurecr.io/uksqqbe002aks01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_uksqqbe002aks01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep uksqqbe002aks01a42b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace uksqqbe002aks01a42b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: uksqqbe002aks01a42b
        container-registry-url: uksqqbe002crc01.azurecr.io
        container-registry-username: ${{ secrets.acr_uksqqbe002crc01_username }}
        container-registry-password: ${{ secrets.acr_uksqqbe002crc01_password }}
        secret-name: uksqqbe002akdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: uksqqbe002aks01a42b
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          uksqqbe002crc01.azurecr.io/uksqqbe002aks01:${{ github.sha }}
        imagepullsecrets: |
          uksqqbe002akdockerauth