on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ctpsserjecr01.azurecr.io
        username: ${{ secrets.acr_ctpsserjecr01_username }}
        password: ${{ secrets.acr_ctpsserjecr01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/WebApplication1" -f  "WebApplication1/Dockerfile" -t ctpsserjecr01.azurecr.io/ctpsserjeaks01:${{ github.sha }}
        docker push ctpsserjecr01.azurecr.io/ctpsserjeaks01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_ctpsserjeaks01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ctpsserjeaks01b24a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ctpsserjeaks01b24a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ctpsserjeaks01b24a
        container-registry-url: ctpsserjecr01.azurecr.io
        container-registry-username: ${{ secrets.acr_ctpsserjecr01_username }}
        container-registry-password: ${{ secrets.acr_ctpsserjecr01_password }}
        secret-name: ctpsserjeaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ctpsserjeaks01b24a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          ctpsserjecr01.azurecr.io/ctpsserjeaks01:${{ github.sha }}
        imagepullsecrets: |
          ctpsserjeaksdockerauth